version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: tdb
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-data:/data/db
    networks:
      - mongo-network
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: user
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongodb:27017/
    networks:
      - mongo-network
    ports:
      - 8081:8081
    depends_on:
      - mongo

networks:
  mongo-network:

volumes:
  mongo-data:
